services:

  nginx:
    build: requirements/nginx/.
    image: nginx
    container_name: nginx
    hostname: nginx_host
    depends_on:
      - wordpress
    ports:
      - "443:443"
    volumes:
        - web:/var/www/html/web
    networks:
      - inception
    env_file:
      - .env
    restart: always

  wordpress:
    build: requirements/wordpress/.
    image: wordpress
    container_name: wordpress
    hostname: wp_host
    depends_on:
      - mariadb
    volumes:
        - web:/var/www/html/web
    networks:
      - inception
    env_file:
      - .env
    secrets:
      - db_password
      - db_root_password
      - wp_admin_password
      - wp_user_password
    restart: always
    

  mariadb:
    build: requirements/mariadb/.
    image: mariadb
    container_name: mariadb
    hostname: mariadb
    volumes:
        - database:/var/lib/mysql
    networks:
      - inception
    env_file:
      - .env
    secrets:
      - db_password
      - db_root_password
    restart: always


networks:
  inception:
    name: inception



volumes:
  web: 
    name: wp_volume
    driver: local
    driver_opts:
      type: none
      device: /home/yushimom/data
      o: bind
  database: 
    name: db_volume
    driver: local
    driver_opts:
      type: none
      device: /home/yushimom/data
      o: bind
 


secrets:
  db_password:
    file: ../secrets/db_password.txt
  db_root_password:
    file: ../secrets/db_root_password.txt
  wp_admin_password:
    file: ../secrets/wp_admin_password.txt
  wp_user_password:
    file: ../secrets/wp_user_password.txt

  
