version: '3.8'

services:

  nginx:
    build: requirements/nginx/.
    container_name: nginx
    hostname: nginx_host
    depends_on:
      - wordpress
    ports:
      - "8080:80"
    volumes:
        - ./web:/var/www/html
    networks:
      inception:
    env_file:
      - .env

  wordpress:
    build: requirements/wordpress/.
    container_name: wp-php
    hostname: wp_host
    depends_on:
      - mariadb
    volumes:
        - ./web:/var/www/html
    networks:
      inception:
    env_file:
      - .env
  
  mariadb:
    build: requirements/mariadb/.
    container_name: mariadb
    hostname: mariadb
    volumes:
        - ./database:/var/lib/mysql
    networks:
      inception:
    env_file:
      - .env
    

networks:
  inception:

volumes:
  web: 
    name: wp_volume
    driver: local
    driver_opts:
      type: none
      device: ./web
      o: bind
  database: 
    name: db_volume
    driver: local
    driver_opts:
      type: none
      device: ./database
      o: bind